### ISSUE TITLE
StemElement cannot be a "term" since it is not a TextElement -- is it correct?

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/isodoc#17]
Is this correct?

**Comment by opoudjis** [comment]
No, stem is a text element.

````
TextElement =
  text | em | eref | strong | stem | sub | sup | tt |
  strike | smallcap | xref | br | hyperlink | hr | pagebreak | bookmark
````

In the UML, stemelement inherits from BasicElement: https://github.com/riboseinc/isodoc-models/blob/master/images/text.png

And terms can be mathematical expressions: t_90_ is an alternate term in the Rice document.

**Comment by ronaldtse** [comment]
Right -- so the UML diagram is wrong and I need to update it, correct?

**Comment by ronaldtse** [comment]
But xref, hyperlink, hr, br, pagebreak, bookmark -- cannot be a Term, right?

**Comment by opoudjis** [comment]
Right on both.

**Comment by ronaldtse** [comment]
Thanks!
