### ISSUE TITLE
Make footnotes look more presentable in HTML

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/isodoc#19]
@ronaldtse, you'll have to tell me what you want the footnotes to look like in the HTML output.

**Comment by ronaldtse** [comment]
I believe ISO directives part 1 contain footnotes? We can just style it their way.

**Comment by opoudjis** [comment]
https://www.iso.org/sites/directives/2017/consolidated/index.xhtml .

Wow. That's not much better than what we have; but at least it'll be easy to do.

**Comment by ronaldtse** [comment]
Frankly if we are to make it pretty and useable we should show the footnote whenever the screen shows the footnote 😉

**Comment by opoudjis** [comment]
That's what I expected you'd want; but once there's HTML in place, you can get anyone to do that...
