### ISSUE TITLE
Term Model: term@identifier rename from "anchor"

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/isodoc#2]

**Comment by opoudjis** [comment]
They're either all \@identifier, or all \@anchor. I'd actually favour anchor, but am OK with identifier. In the schema, I'm strongly inclined to make them just id.

**Comment by ronaldtse** [comment]
Fixed in https://github.com/riboseinc/isodoc-models/commit/a04043293e4461a5273ffc8522736faf5082d4b9

**Comment by ronaldtse** [comment]
Renamed all `identifier`s to `id`s in https://github.com/riboseinc/isodoc-models/commit/cbcb7d651d4c5307c36a8e91681370ee90b8d5bb
