### ISSUE TITLE
A better representation of ISO HTML

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/isodoc#21]
Today's style of ISO HTML isn't very pretty or useable:
https://www.iso.org/sites/directives/2017/consolidated/index.xhtml#footnote-003-backlink

Maybe there should be an alternative style, with these features:

* TOC in sidebar, highlighting current section
* relevant footnote entry appears dynamically when footnote citation in view
* anchors named according to the section name

**Comment by opoudjis** [comment]
This has now been done.
