### ISSUE TITLE
Formula referencing

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/isodoc#27]
Formulae are referenced by container and formula number; e.g. "see A.2, Formula (A.5)."

For all container referencing, the container is skipped if we are currently in that container: if we are in A.2, we just reference "Formula (A.5)."

**Comment by ronaldtse** [comment]
That's probably because ISO documents are being manually validated instead of mechanically -- that's more the reason we should automate this. 

For the record, here's the specific entry in Directives Part 2:

> 27.4	Referencing
> If a formula is numbered, it should be referred to in the text. The purpose of a formula should be made clear by its context, for example, with an introductory proposition.
> 
> Use, for example, the following forms for references to mathematical formulae:
> •	“see 10.1, Formula (3)”;
> •	“see A.2, Formula (A.5)”.
