### ISSUE TITLE
Ensuring references follow Directives Part 2

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/isodoc#29]
@opoudjis you probably have gone through this but ideally we should document in the README how the references are being rendered.

In Directives Part 2, https://www.iso.org/sites/directives/2016/part2/index.xhtml different referential targets have a different way of rendering:

> 22.4	Referencing
> Clauses and subclauses need not be specifically referred to in the text.
> Use, for example, the following forms for references to clauses and subclauses:
> •	“in accordance with Clause 4”;
> •	“details as given in 4.1.1”;
> •	“the requirements given in B.2”;
> •	“the methods described in 5.3 provide further information on...”.

> 23.4	Referencing
> The purpose of a list should be made clear by its context. For example, an introductory proposition or a subclause title can serve to introduce the list. Lists need not be specifically referred to in the text.
> If cross-references to list items are necessary, a numbered list shall be used. Within a subdivision, each list item in a numbered list shall have a unique identifier. Numbering restarts at each new clause or subclause.
> Use, for example, the following forms for references to lists:
> •	“as specified in 3.1 b)”;
> •	“the requirements given in B.2 c)”.

> 24.4	Referencing
> Notes need not be specifically referred to in the text.
> If notes are referred to, use for example, the following forms for references:
> •	“an explanation is provided in 7.1, Note 2”;
> •	“see 8.6, Note 3”.

> 25.4	Referencing
> Examples need not be specifically referred to in the text.
> If examples are referred to, use for example, the following forms for references:
> •	“see 6.6.3, Example 5”;
> •	“Clause 4, Example 2 lists …”.

> 27.4	Referencing
> If a formula is numbered, it should be referred to in the text. The purpose of a formula should be made clear by its context, for example, with an introductory proposition.
> Use, for example, the following forms for references to mathematical formulae:
> •	“see 10.1, Formula (3)”;
> •	“see A.2, Formula (A.5)”.

> 28.4	Referencing
> Each figure shall be explicitly referred to within the text.
> Use, for example, the following forms for references to figures and subfigures:
> •	“Figure 3 illustrates…”;
> •	“See Figure 6 b)”.

> 29.4	Referencing
> Each table shall be explicitly referred to within the text.
> Use, for example, the following forms for references to tables:
> •	“Table 3 lists…”;
> •	“See Table B.1”.

**Comment by opoudjis** [comment]
That is in fact what I've been doing, but I missed the lists. (This also means that they presume only one list per clause, which is naive.) I'll keep this ticket for the README update, and I'll make a separate ticket for lists.

**Comment by ronaldtse** [comment]
Maybe what can be inferred is that each clause should only contain one list at most. It would be difficult to say, “find 3.2.1 List 2 c)”.

**Comment by opoudjis** [comment]
That's a should, not a must, though: it's not a must unless they spell it out, surely. I'll be issuing warnings if there's an anchor in a list and there's more than one list in a clause. (And I'll ignore anchors in unordered lists, again with a warning.) But I will in fact generate "3.2.1 List 2 c" as a reference, because I have to generate something.

**Comment by opoudjis** [comment]
Added explanation to https://github.com/riboseinc/asciidoctor-iso/wiki/Guidance-for-authoring

List issue is https://github.com/riboseinc/isodoc/issues/30

**Comment by ronaldtse** [comment]
Nicely done -- thanks @opoudjis !
