### ISSUE TITLE
List item crossreferencing

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/isodoc#30]
> 23.4	Referencing
> The purpose of a list should be made clear by its context. For example, an introductory proposition or a subclause title can serve to introduce the list. Lists need not be specifically referred to in the text.
> If cross-references to list items are necessary, a numbered list shall be used. Within a subdivision, each list item in a numbered list shall have a unique identifier. Numbering restarts at each new clause or subclause.
> Use, for example, the following forms for references to lists:
> •	“as specified in 3.1 b)”;
> •	“the requirements given in B.2 c)”.

**Comment by ronaldtse** [comment]
Btw is this doable with asciidoctor input?

**Comment by opoudjis** [comment]
Yes, just. I need to make sure list item anchors are not conflated by Asciidoc with in-text bookmarks, but I think they aren't. (And if they are, I'll distinguish between them through their position.)

**Comment by opoudjis** [comment]
> Maybe what can be inferred is that each clause should only contain one list at most. It would be difficult to say, “find 3.2.1 List 2 c)”.
 
>That's a should, not a must, though: it's not a must unless they spell it out, surely. I'll be issuing warnings if there's an anchor in a list and there's more than one list in a clause. (And I'll ignore anchors in unordered lists, again with a warning.) But I will in fact generate "3.2.1 List 2 c" as a reference, because I have to generate something.

**Comment by opoudjis** [comment]
asciidoctor-iso modified to have links to list items. It is not supported by Asciidoctor, but I convert the first bookmark in a list item into an ID
