### ISSUE TITLE
Internationalise

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/isodoc#47]
Need output to deal with at least English, French, Chinese, and Russian. The metalanguage needs to be translated.

**Comment by opoudjis** [comment]
I need the following Chinese, @ronaldtse:

ISO and IEC maintain terminological databases for use in
      standardization at the following addresses:

All Parts (in ISO references)

**Comment by opoudjis** [comment]
Those apart, Chinese localisation done.

Will do French localisation. Then, will create YAML module to extend localisation to arbitrary language.

**Comment by opoudjis** [comment]
Consulting https://isotc.iso.org/livelink/livelink/fetch/2000/2122/4230450/4230454/Directives_ISO_IEC%2C_Partie_2_—_Principes_et_règles_de_structure_et_de_rédaction_des_documents_ISO_et_IEC_%28Septième_édition%2C_2016%29.pdf?nodeid=18492619&vernum=-2

**Comment by opoudjis** [comment]
French done. YAML done and tested.

Will close ticket once I've tidied asciidoctor-csd and asciidoctor-gb downstream.

**Comment by ronaldtse** [comment]
Chinese translations

> ISO and IEC maintain terminological databases for use in standardization at the
following addresses:
=>
> ISO和IEC用于标准化的术语数据库地址如下：

> * ISO Online browsing platform: available at http://www.iso.org/obp
> * IEC Electropedia: available at http://www.electropedia.org
=>
> * ISO在线浏览平台： 位于 http://www.iso.org/obp
> * IEC Electropedia： 位于 http://www.electropedia.org

> All Parts
> 所有部分
