### ISSUE TITLE
Use templating language instead of `gsub`

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/isodoc#5]
HTML templates are currently "filled-in" within isodoc using `gsub`. If the content included a phrase like `For CSS we should use SCSS templates as you can see in asciidoctor-reveal.js` (a key that is being replaced), then the templating won't work properly.

We should use template engines to interpolate the HTML instead. 

For example, [asciidoctor-reveal.js](https://github.com/asciidoctor/asciidoctor-reveal.js) uses the Slim template language. Personally, I think we can use the [Liquid template language](https://github.com/Shopify/liquid) to create HTML templates.

This way the content of the templates can be easily changed.

**Comment by opoudjis** [comment]
Will be painless to move to Liquid

**Comment by ronaldtse** [comment]
Awesome thanks!

**Comment by opoudjis** [comment]
Done for all three standards formats.
