### ISSUE TITLE
Refactor word html generation

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/isodoc#56]
Word HTML generation shall not be a subclass of HTML generation, but a sibling class. Both will inherit common methods from a superclass, if necessary.

**Comment by ronaldtse** [comment]
Goal of the normal HTML generation is to be as semantically clean as possible in HTML 5. A real "native" HTML.

Word HTML can be however convoluted necessary 😉

**Comment by opoudjis** [comment]
With the exception of the comments (which should be redone anyway as a result of https://github.com/riboseinc/isodoc-style/issues/3), the HTML output is already clean; the WordSection1, 2, 3 divs are inherited from Word, but they are useful for dividing up the content.

**Comment by ronaldtse** [comment]
@opoudjis can we not have the WordSection divs but rather separate them into header ("id=front-matter"), section ("id=main") and footer ("id=backmatter")? (something like that?)

**Comment by opoudjis** [comment]
title, prefatory, main: there is no back matter outside of m3d (where it is labelled colophon).

**Comment by opoudjis** [comment]
Done

**Comment by ronaldtse** [comment]
@opoudjis re: colophon -- ISO and GB "published" documents do have an end cover page. Does this count?

GM last page
<img width="646" alt="gm-last-page" src="https://user-images.githubusercontent.com/11865/41207550-26d73d4c-6d53-11e8-8d58-c7332e3a6138.png">

ISO last page
<img width="646" alt="iso-last-page" src="https://user-images.githubusercontent.com/11865/41207578-6e2154f8-6d53-11e8-8668-d6eebb4f5949.png">

**Comment by opoudjis** [comment]
Do we have enough information to generate the GB? 

I guess we have enough information to generate the ISO, but could you confirm whether we should?

**Comment by ronaldtse** [comment]
GB last page in English
<img width="646" alt="gm-last-page" src="https://user-images.githubusercontent.com/11865/41211126-64d07eb6-6d70-11e8-8c22-6fe52f66aa5b.png">

I don't think we have full information for it, and possibly this content is not rule based. 

GB: let's only generate the first section of the colophon (before the first `*`)

ISO: let's generate the ISO one.

**Comment by opoudjis** [comment]
If I can't get the number of pages ahead of time for ISO or GB, are you OK if I output a placeholder value? In fact, if I just put placeholders in, production can always populate them later.

**Comment by ronaldtse** [comment]
Absolutely. Let’s not concern ourselves too much with page numbering for now.
