### ISSUE TITLE
Incompatibility with Ruby 2.5

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/isodoc#58]
Under Ruby 2.5, the code block with `**p` will return an error in parsing.

**Comment by opoudjis** [comment]
This appears to be Rubocop poorly implementing an upcoming Ruby 2.6 warning, and the cop has already been disabled: https://github.com/rubocop-hq/rubocop/issues/5887, https://github.com/rubocop-hq/rubocop/commit/9f976de2aa17203d692dcf1df921ecdbeacb78d1

> Rubocop 0.56 seems to warn about all possible usages of **options, whereas a recent ruby 2.6.0dev only warns about some very specific usages where the method is defined to take a hash as a positional argument instead of keyword arguments.

> What this cop was trying to realize is emulating experimental
warnings for Ruby 2.6. And that is something of the future.
So this PR will remove this cop until the prospect of existing
problem solving.

I dislike Rubocop, you won't be surprised to hear. I hate even more that they're issuing warnings about versions of the language that aren't even published yet; and the fact that they're getting those warnings *wrong* is just contemptible.

**Comment by ronaldtse** [comment]
It’s not about rubocop — it’s a real runtime crash... will find you the block later.

**Comment by ronaldtse** [comment]
This line fails on Ruby 2.5:

https://github.com/riboseinc/isodoc/blob/88163d2cabf1b7eea4f32a2ae038023f38ebd201/lib/isodoc/iso2wordhtml.rb#L90

Ruby 2.5 thinks that there are two blocks.

**Comment by opoudjis** [comment]
Resolved all instances: wrapped double splat function arguments in parens.
