### ISSUE TITLE
Use SCSS/SASS templates for CSS code

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/isodoc#6]
Currently we use raw CSS for Word HTML and normal HTML.

It would be much cleaner to use SCSS (used in [asciidoctor-reveal.js](https://github.com/asciidoctor/asciidoctor-reveal.js)) or SASS to generate CSS as they support inheritance and inclusion.

**Comment by opoudjis** [comment]
Will be doing CSS inheritance

**Comment by opoudjis** [comment]
Put SACC engine inside each of asciidoctor-iso, asciidoctor-gb, asciidoctor-csd.

**Comment by opoudjis** [comment]
And had to tweak the Word CSS stylesheets, which weren't quite compliant with CSS style.
