### ISSUE TITLE
Refactor ISO-specific content out

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/isodoc#64]
Relates to https://github.com/riboseinc/asciidoctor-iso/issues/62

There is already an Isodoc::ISO subclass within the isodoc gem. This class needs to move to asciidoctor-iso, consistent with how all other asciidoctor-* gems handle isodoc.

ISO-specific functionality needs to migrate to Isodoc::ISO, so that the isodoc gem expresses standardDoc functionality, and can be inherited by other gems with minimal undoing of ISO specifics.

There isn't that much in the way of ISO-specific functionality in Isodoc: the separation of preface into foreword and introduction, the addition of appendixes to annexes.

**Comment by ronaldtse** [comment]
Agreed, thanks!

**Comment by opoudjis** [comment]
Oh, and metadata processing specific to ISO (and overridden in most other gems): status instead of stage/substage; subtitle as a specifically French title.
