### ISSUE TITLE
multiple _images directories overwriting each other

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/isodoc#66]
HTML output under isodoc creates a new `_images` directory for all images to be included with the HTML document, and wipes it clean for each iteration of running isodoc.

metanorma-iso generates an *.html file and an *_alt.html file which share the `_images` directory. Because the _images directory is wiped on each iteration of generating an HTML file, and the image file names are regenerated as GUIDs, that means that one HTML file cannot access its outputs.

The proximal fix is to rename the _images directory to use the filename it will be associated with, to prevent this kind of conflict.

**Comment by ronaldtse** [comment]
I wonder if we should package the HTML (and other output) in a separate directory all together because it makes life easier with distribution (right now I have to make a new directory, copy the deliverables in it, and then zip it).

**Comment by opoudjis** [comment]
That should be optional behaviour, and I think it's an option in the metanorma script.

**Comment by ronaldtse** [comment]
You mean in the `metanorma-cli` gem? Do we have this option now?

**Comment by ronaldtse** [comment]
Cool, let’s add a ticket there.
