### ISSUE TITLE
No list bullets within example cells in Word

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/isodoc#70]
As a result of the #69 fix with Word HTML native lists, there is now a new issue: lists embedded within tables (such as examples) have flush left margins. As a result, their bullets are to the left of the table cell, and are not being displayed. The different indentations of lists are also being lost: Word is treating all list entries as the same, and is interpolating the style command "text-indent:-18.0pt" regardless of depth.

Without a container, it is not clear that there is a CSS solution to this.

**Comment by opoudjis** [comment]
Solution is to suppress the CSS instruction to set the margin on "td.example p". Solved in metanorma-iso and other stylesheets.

**Comment by ronaldtse** [comment]
Awesome thanks 👍
