### ISSUE TITLE
List "rake" as a gem dependency

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/isodoc#77]
`isodoc`'s usage of `sassc` makes it dependent on the `rake` gem, which has been added as a real dependency in SassC 2.0.0. However, I still can't install SassC 2.0.0 properly.

(https://github.com/sass/sassc-ruby/issues/86)

Should we list "rake" as a gem dependency?

Closing https://github.com/riboseinc/relaton/issues/18 in favor of this.

**Comment by opoudjis** [comment]
I'm... astonished they regard this issue as "fixed". But then, my CTO warned me about the dependency hell of Ruby libraries. (Golang is even worse, and the one time I tried using godep was a disaster.)
