### ISSUE TITLE
Allow subtitles

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/isodoc#78]
As title type=alt, in the first instance

**Comment by ronaldtse** [comment]
Should we just model the subtitle as the next title part like in ISO?

**Comment by opoudjis** [comment]
unece has implemented `subtitle` as an ad hoc solution to this, but I want not to do things that way.

**Comment by opoudjis** [comment]
I will allow "subtitle" as a type of title: "alt" is not quite right.
