### ISSUE TITLE
Spurious footnote repetition

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/isodoc#83]
In HTML, the same footnote number is assigned to two footnotes if they have the same content. `https://nvd.nist.gov/[https://nvd.nist.gov/]` and `https://scap.nist.gov/revision/1.3/#tools[https://scap.nist.gov/revision/1.3/#tools]` are being considered the same footnote, and as a result the second footnote is not being generated.

**Comment by opoudjis** [comment]
Alas, that appears to be an Asciidoctor issue, not a Metanorma issue: Asciidoctor itself considers those footnotes to be identical, and assigns them the same reference number (`node["reference"]`). I am dodging this only by adding text to one of the two footnotes.

**Comment by opoudjis** [comment]
Raised https://github.com/asciidoctor/asciidoctor/issues/2994,  but this will not likely be fixed in a hurry, if at all. We will have to tell users that footnotes consisting only of links are to be avoided, and even that adding text will not make them distinct, since the hyperlink itself is ignored.

The only workaround I can find is to use `footnoteref:[id,text]` instead of `footnote:[text]`, as `footnoteref` enforces distinct identifiers for footnotes. That has its own issue: `footnoteref` rejects `link[]` formatting, as it grabs the first close-bracket it finds, so the hyperlink cannot be to any text; Asciidoctor processing of macros is known to be unsophisticated.

**Comment by opoudjis** [comment]
The workaround that works fully is: `footnoteref:[id,link:url[]]`. Keep issue open so I can document this as a gotcha.

**Comment by mojavelinux** [comment]
If you print `doc.catalog[:footnotes]` you should find unique entries for every footnote.

**Comment by mojavelinux** [comment]
:+1:

If you need more assistance, just let me know.

**Comment by opoudjis** [comment]
Nope, confirmed, all good. Sorry about that. Will cancel the other issue.

**Comment by opoudjis** [comment]
Fixed in metanorma-standoc.
